---
global:
  pattern: ansible-edge-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  hub:
    provider: aws
    storageClassName: gp2

main:
  clusterGroupName: hub

ansible_python_interpreter: /usr/local/bin/python3
# this is a change
